import logging
import os
import datetime

logging.basicConfig(level=logging.INFO)

LOG_FILE=f"logs_{datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.log"# this line creates a log file name with the current date and time in the format "logs_YYYY-MM-DD_HH-MM-SS.log". The datetime module is used to get the current date and time, and strftime() method is used to format it as a string. This log file will be used to store log messages generated by the application.
LOG_PATH = os.path.join(os.getcwd(), "logs", LOG_FILE)# this line creates a path for the log file by joining the current working directory (os.getcwd()), the "logs" folder, and the log file name (LOG_FILE) using os.path.join(). This ensures that the log file is created in a "logs" folder within the current working directory. If the "logs" folder does not exist, it will be created in the next line.
os.makedirs(os.path.dirname(LOG_PATH), exist_ok=True)# this line creates the "logs" folder if it does not already exist. os.path.dirname(LOG_PATH) gets the directory part of the LOG_PATH, and os.makedirs() creates the directory. The exist_ok=True argument allows the function to succeed even if the directory already exists, preventing any errors from being raised.
LOG_FILE_PATH = os.path.join(os.getcwd(), "logs", LOG_FILE)
logging.basicConfig(   # this line configures the logging module to write log messages to the specified log file (LOG_FILE_PATH) with a logging level of INFO. The format of the log messages is defined, including the timestamp, log level, and message content. The datefmt argument specifies the format for the timestamp in the log messages.
    filename=LOG_FILE_PATH,
    level=logging.INFO,
    format='[%(asctime)s] %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
if __name__ == "__main__":
    logging.info("Logger initialized. Log file created at: %s", LOG_FILE_PATH)